name: Selenium Github Action
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
        with:
          ref: "bot"

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installing package list
        run: apt list --installed

      - name: Removing previous chrome instances on runner
        run: sudo apt purge google-chrome-stable  
       
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay beautifulsoup4 secure-smtplib python-dotenv 

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Running the Python script
        run: python logger.py -n
      
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          author_name: "Github Actions Bot"
