name: Selenium Github Action
on:
  schedule:
    - cron: "0 18 */2 * *"
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    environment: bot
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
        with:
          ref: "bot"

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt


      - name: Removing previous chrome instances on runner
        run: sudo apt purge google-chrome-stable  
       
      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Running the Python script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DEV: ${{ vars.DEV }}
          RECIPIENT_EMAILS: ${{ vars.RECIPIENT_EMAILS }}
        run: python logger.py
      
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actor
