name: Update Bot Branch
on:
  push:
    branches:
      - 'master'
jobs:
  update-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: "bot"

      - name: Rebase master
        run: git rebase origin master

      - name: Git Push
        run: git push
